name: Build
on:
  push:
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: twitter-likes
      - name: smoke test
        run: |
          # Use the local image for tests
          # Make sure there is no ModuleNotFoundError. 
          docker run --rm twitter-likes /scripts/get_liked_tweets.py 2>&1 > output || true
          if grep ModuleNotFoundError output; then
            echo "Docker image fails with ModuleNotFoundError. Base distroless image\'s python version has likely increased"
            cat output
            exit 1
          fi

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          # defaults: schedule and ref types
          # Additional: Set sha tag for each image
          # And: Main branch is latest for now 
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=sha,prefix=,format=short
            type=raw,enable=${{ github.ref == 'refs/heads/main' }},value=latest
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}